$typeCode=org.metavm.object.type.Index
org.metavm.application.AppInvitation.IDX_APP=01aae20102
org.metavm.beans.BeanDefinitionRegistry.IDX_ALL_FLAGS=0192e10102
org.metavm.ddl.Commit.IDX_RUNNING=01aae10102
org.metavm.flow.Function.IDX_ALL_FLAG=01dee10102
org.metavm.flow.Function.UNIQUE_NAME=01dee10104
org.metavm.message.Message.IDX_TARGET=019ce00102
org.metavm.object.instance.ChangeLog.IDX_STATUS=01f2de0102
org.metavm.object.type.GlobalKlassTagAssigner.IDX_ALL_FLAGS=01e2e20102
org.metavm.object.type.Klass.IDX_ALL_FLAG=01c6df0102
org.metavm.object.type.Klass.IDX_NAME=01c6df0104
org.metavm.object.type.Klass.UNIQUE_QUALIFIED_NAME=01c6df0106
org.metavm.object.type.Klass.UNIQUE_SOURCE_TAG=01c6df0108
org.metavm.object.type.KlassSourceCodeTagAssigner.IDX_ALL_FLAGS=018ae20102
org.metavm.object.type.KlassTagAssigner.IDX_ALL_FLAGS=01aadf0102
org.metavm.object.type.StaticFieldTable.IDX_KLASS=01d4e10102
org.metavm.task.ExecutorData.IDX_AVAIlABLE=01b6e20102
org.metavm.task.ExecutorData.IDX_IP=01b6e20104
org.metavm.task.SchedulerRegistry.IDX_ALL_FLAG=01acde0102
org.metavm.task.ShadowTask.IDX_EXECUTOR_IP_START_AT=01e2df0104
org.metavm.task.ShadowTask.IDX_RUN_AT=01e2df0102
org.metavm.task.Task.IDX_STATE_LAST_RUN_AT=01aade0102
org.metavm.user.LoginAttempt.IDX_CLIENT_IP_SUCC_TIME=01a8e00104
org.metavm.user.LoginAttempt.IDX_LOGIN_NAME_SUCC_TIME=01a8e00102
org.metavm.user.PlatformUser.IDX_APP=01a4e00102
org.metavm.user.Session.IDX_TOKEN=0180e30104
org.metavm.user.Session.IDX_USER_STATE=0180e30102
org.metavm.user.User.IDX_LOGIN_NAME=01aedf0104
org.metavm.user.User.IDX_PLATFORM_USER_ID=01aedf0102
org.metavm.user.VerificationCode.IDX=01eedf0102
org.metavm.user.VerificationCode.IDX_CLIENT_IP_CREATED_AT=01eedf0104
org.metavm.view.ListView.IDX_TYPE_PRIORITY=01bae30102
