$typeCode=org.metavm.object.type.StaticFieldTable
java.io.ObjectStreamConstants=01c8dd013e
java.lang.Byte=01dcdd0168
java.lang.Character=01bcd901c00c
java.lang.Double=01d8d8018e01
java.lang.Float=01e0dd019a01
java.lang.Integer=01b4db018802
java.lang.Long=01fed9018402
java.lang.Short=01dedd016c
java.lang.Thread=018ada01ba02
java.lang.invoke.MethodHandleInfo=01b4dc0136
java.lang.invoke.MethodHandles.Lookup=01fcd8019e04
java.lang.reflect.Member=01b2dc0110
java.util.Spliterator=01ccd80178
