spring:
  main:
      allow-circular-references: true
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 85263670
      url: jdbc:mysql://localhost:3306/object?allowMultiQueries=true
  data:
      elasticsearch:
        host: localhost
        port: 9200
        user: elastic
        password: 85263670
  jackson:
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: tech.nonocode.object.meta.persistence
  type-handlers-package: tech.metavm.util

metavm:
  resource-cp-root: /Users/leen/workspace/object/src/main/resources
  token:
    encrypt:
      certificate: /etc/metavm/encrypt_key.pub
      key: /etc/metavm/encrypt_key
    sign:
      certificate: /etc/metavm/sign_key.pub
      key: /etc/metavm/sign_key
  id:
    file:
      Type: /id/Type.properties
      Field: /id/Field.properties
      UniqueConstraintRT: /id/Constraint.properties
      TypeCategory: /id/TypeCategory.properties