spring:
  main:
    allow-circular-references: true
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 85263670
      url: jdbc:postgresql://127.0.0.1:5432/object
      hikari:
        maximum-pool-size: 10
        minimum-idle: 0
    secondary:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 85263670
      url: jdbc:postgresql://127.0.0.1:5432/object
      hikari:
        maximum-pool-size: 1
        minimum-idle: 0
  #    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 85263670
#    url: jdbc:mysql://localhost:3306/object?allowMultiQueries=true
  data:
    elasticsearch:
      host: localhost
      port: 9200
      user: elastic
      password: 85263670
    redis:
      host: 127.0.0.1
      port: 6379
  jackson:
    default-property-inclusion: non_null

smtp:
  host: smtp.163.com
  port: 465
  username: 15968879210@163.com
  password: 85263670

server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024

management.health.elasticsearch.enabled: false

metavm:
  resource-cp-root: /Users/leen/workspace/kiwi/model/src/main/resources
  api:
    verify: true
  token:
    encrypt:
      certificate: /etc/metavm/encrypt_key.pub
      key: /etc/metavm/encrypt_key
    sign:
      certificate: /etc/metavm/sign_key.pub
      key: /etc/metavm/sign_key
  id:
    file:
      Type: /id/Type.properties
      Field: /id/Field.properties
      UniqueConstraintRT: /id/Constraint.properties
      TypeCategory: /id/TypeCategory.properties
  ddl:
    disable-task-delay: false