###
POST https://api.metavm.tech/rest/bootstrap?saveIds=false

###
GET https://api.metavm.tech/websocket/metavm-websocket
Upgrade: websocket

###
POST https://api.metavm.tech/rest/bootstrap/save

###
POST https://api.metavm.tech/rest/application/create
Accept: application/json
Content-Type: application/json

{
  "name": "test",
  "rootPassword": "123456"
}

###
POST https://api.metavm.tech/rest/login
Accept: application/json
Content-Type: application/json

{
  "appId": 1007900159,
  "loginName": "admin",
  "password": "123456"
}

###
DELETE https://api.metavm.tech/rest/instance/7205760404292733

###
GET https://api.metavm.tech/rest/system/cache/1005400109

