
GET https://api.metavm.tech/rest/instance/1000600045

<> 2023-02-22T151012.200.json
<> 2023-02-22T150945.401.json
###
PUT https://api.metavm.tech/object/product
Content-Type: application/json
X-App-ID: 1001500031

{
  "title": "Shoes",
  "price": 100.0,
  "quantity": 100
}

###
POST https://api.metavm.tech/object/user-service/get-user-by-name
Content-Type: application/json
X-App-ID: 1001500031

[
  "leen"
]
###
GET https://api.metavm.tech/object/org/metavm/mlab/ProductKind/DEFAULT
X-App-ID: 1000000019

###
GET https://api.metavm.tech/object/org/metavm/mlab/Currency/YUAN
X-App-ID: 1000000019

###
PUT https://api.metavm.tech/object/org/metavm/mlab/Product
X-App-ID: 1000000019
Content-Type: application/json

{
  "name": "Shoes",
  "kind": "01dea8d6b90700",
  "skus": [
    {
      "name": "40",
      "price": {
        "amount": 100,
        "currency": "01d8a8d6b90700"
      },
      "inventory": {
        "quantity": 100
      }
    }
  ]
}

