###
PUT http://localhost:8080/object/shopping/product
X-App-ID: 1000000026
Content-Type: application/json

{
  "name": "T-Shirt",
  "skus": [
    {
      "variant": "Default",
      "price": 100,
      "stock": 100
    }
  ]
}

###
GET http://localhost:8080/object/019cb8d6b90700
X-App-ID: 1000000026

###
POST http://localhost:8080/object/019cb8d6b90702/decrement-stock
X-App-ID: 1000000026
Content-Type: application/json

{
  "amount": 1
}

###
PUT http://localhost:8080/object/shopping/direct-coupon
X-App-ID: 1000000026
Content-Type: application/json

{
  "product": "01d2d9d6b90700",
  "discount": 10
}

###
POST http://localhost:8080/object/order-service/place-order
X-App-ID: 1000000026
Content-Type: application/json

{
  "sku": "019cb8d6b90702",
  "quantity": 1,
  "coupons": []
}

###
GET http://localhost:8080/object/01d8d9d6b90700
X-App-ID: 1000000026

###
GET http://localhost:8080/object/018cd9d6b90700
X-App-ID: 1000000026

###
POST http://localhost:8080/object/product-service/find-by-title
X-App-ID: 1000000026
Content-Type: application/json

[
  "Hat"
]

###
POST http://localhost:8080/object/product-service/count-by-price
X-App-ID: 1000000026
Content-Type: application/json

[
  500, 1000
]

###
POST http://localhost:8080/object/search/shopping/product
X-App-ID: 1000000026
Content-Type: application/json

{
  "name": "Hat"
}
