POST http://metavm.tech:9090/bootstrap?saveIds=false

###
POST http://metavm.tech:9090/system/init-test

###
POST http://metavm.tech:9090/bootstrap/init-root-application
Accept: application/json


###
POST http://metavm.tech:9090/login
Content-Type: application/json
Accept: application/json

{
  "appId": 1,
  "loginName": "admin",
  "password": "123456"
}

<> 2023-01-24T212755.200.json


###
GET http://metavm.tech:9090/type/13054

###
POST http://metavm.tech:9090/bootstrap/init-root-application
Accept: application/json

###
POST http://metavm.tech:9090/application/repair/1000100003
Accept: application/json

###
POST http://metavm.tech:9090/bootstrap/rebuild-index
Accept: application/json
