package tech.metavm.expression;

public enum TokenType {
    VARIABLE,
    OPERATOR,
    KEYWORD,
    INTEGER,
    FLOAT,
    BOOLEAN,
    SINGLE_QUOTED_STRING,
    DOUBLE_QUOTED_STRING,
    NULL,
    OPEN_PARENTHESIS,
    CLOSING_PARENTHESIS,
    FUNCTION,
    OPEN_BRACKET,
    CLOSING_BRACKET
}
