###
POST https://metavm.tech/api/bootstrap?saveIds=false

###
POST https://metavm.tech/api/bootstrap/save

###
POST https://metavm.tech/api/tenant/create
Accept: application/json
Content-Type: application/json

{
  "name": "test",
  "rootPassword": "123456"
}

###
POST https://metavm.tech/api/login
Accept: application/json
Content-Type: application/json

{
  "tenantId": 1000400009,
  "loginName": "admin",
  "password": "123456"
}

###
DELETE https://metavm.tech/api/instance/7205760404292733

###
GET https://metavm.tech/api/management/cache/1005400109

